global using Basket.Events;
global using Basket.Models;
global using Shared.Common;
global using Shared.DDD;
global using Catalog.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;